import type { Metadata } from "next";
import { Bug, Handshake, HelpCircle, LockKeyhole, Mail, MapPinned } from "lucide-react";
import { ContentPage } from "@/components/ContentPage";

export const metadata: Metadata = { title: "Contact", description: "Contact ClassicsGo support, listings, partnerships, privacy or security.", alternates: { canonical: "/contact" } };

const contacts = [
  { email: "support@classicsgo.com", title: "Account and app support", text: "Signing in, account access or a problem using the site.", icon: <HelpCircle /> },
  { email: "info@classicsgo.com", title: "Event listing updates", text: "Missing, changed or cancelled event information.", icon: <MapPinned /> },
  { email: "hello@classicsgo.com", title: "Clubs and partnerships", text: "Club calendars, venues, local firms and future partnerships.", icon: <Handshake /> },
  { email: "privacy@classicsgo.com", title: "Privacy requests", text: "Access, correction, deletion or another data-rights request.", icon: <LockKeyhole /> },
  { email: "security@classicsgo.com", title: "Security reports", text: "Report a suspected vulnerability responsibly. Please do not include passwords or tokens.", icon: <Bug /> }
];

export default function ContactPage() {
  return <ContentPage eyebrow="Contact" title="Speak to the right ClassicsGo inbox." intro="Choose the address that best matches your question. We use dedicated ClassicsGo email aliases so requests reach the right queue."><div className="grid gap-4 sm:grid-cols-2">{contacts.map((contact) => <a key={contact.email} href={`mailto:${contact.email}`} className="rounded-xl border border-ink/10 bg-paper p-5 shadow-sm transition hover:border-racing/30"><span className="text-racing">{contact.icon}</span><h2 className="mt-3 text-lg font-black">{contact.title}</h2><p className="mt-1 text-sm leading-6 text-muted">{contact.text}</p><span className="mt-3 inline-flex items-center gap-2 text-sm font-bold text-racing"><Mail className="h-4 w-4" />{contact.email}</span></a>)}</div><h2>About service emails</h2><p>Messages generated by ClassicsGo may use <strong>notifications@classicsgo.com</strong> or <strong>noreply@classicsgo.com</strong>. Those addresses are not monitored; reply to support@classicsgo.com instead.</p></ContentPage>;
}
