import type { AgentRun, ClassicEvent, ReviewQueueItemType } from "@/lib/types";

export const sampleEvents: ClassicEvent[] = [
  {
    id: "sample-1",
    title: "Bicester Heritage Scramble",
    slug: "bicester-heritage-scramble-2026",
    description: "A relaxed open-day gathering with historic motoring specialists, club displays and food around the former RAF site.",
    event_type: "Classic car show",
    start_date: "2026-06-21",
    start_time: "09:00",
    end_date: null,
    end_time: null,
    venue_name: "Bicester Heritage",
    address: "Buckingham Road",
    town: "Bicester",
    county: "Oxfordshire",
    postcode: "OX27 8AL",
    latitude: 51.9159,
    longitude: -1.1401,
    price_text: "Advance tickets",
    booking_required: true,
    booking_url: "https://bicesterheritage.co.uk/",
    organiser_name: "Bicester Heritage",
    organiser_url: "https://bicesterheritage.co.uk/",
    image_url: null,
    status: "published",
    confidence_score: 90,
    is_verified: true,
    source_count: 2,
    last_checked_at: "2026-05-01T09:00:00Z"
  },
  {
    id: "sample-2",
    title: "Brooklands Summer Classic Gathering",
    slug: "brooklands-summer-classic-gathering",
    description: "Classic cars, period displays and museum access at one of Britain's most important motoring venues.",
    event_type: "Museum / venue event",
    start_date: "2026-07-12",
    start_time: "10:00",
    end_date: null,
    end_time: null,
    venue_name: "Brooklands Museum",
    address: "Brooklands Drive",
    town: "Weybridge",
    county: "Surrey",
    postcode: "KT13 0SL",
    latitude: 51.3536,
    longitude: -0.4656,
    price_text: "Museum admission applies",
    booking_required: false,
    booking_url: "https://www.brooklandsmuseum.com/",
    organiser_name: "Brooklands Museum",
    organiser_url: "https://www.brooklandsmuseum.com/",
    image_url: null,
    status: "published",
    confidence_score: 86,
    is_verified: true,
    source_count: 1,
    last_checked_at: "2026-05-02T10:00:00Z"
  },
  {
    id: "sample-3",
    title: "Haynes Breakfast Club Classics",
    slug: "haynes-breakfast-club-classics",
    description: "Cars and coffee style Sunday meet for classic, sports and interesting vehicles at Haynes Motor Museum.",
    event_type: "Cars & coffee",
    start_date: "2026-05-17",
    start_time: "08:30",
    end_date: null,
    end_time: null,
    venue_name: "Haynes Motor Museum",
    address: "Sparkford",
    town: "Yeovil",
    county: "Somerset",
    postcode: "BA22 7LH",
    latitude: 51.0396,
    longitude: -2.5607,
    price_text: "Free meet, museum extra",
    booking_required: false,
    booking_url: "https://www.haynesmuseum.org/",
    organiser_name: "Haynes Motor Museum",
    organiser_url: "https://www.haynesmuseum.org/",
    image_url: null,
    status: "published",
    confidence_score: 82,
    is_verified: false,
    source_count: 1,
    last_checked_at: "2026-05-03T08:30:00Z"
  },
  {
    id: "sample-4",
    title: "Newark Autojumble and Classic Parts Day",
    slug: "newark-autojumble-classic-parts-day",
    description: "Autojumble stalls, restoration parts, automobilia and club parking for classic vehicle owners.",
    event_type: "Autojumble",
    start_date: "2026-06-07",
    start_time: "09:00",
    end_date: null,
    end_time: null,
    venue_name: "Newark Showground",
    address: "Lincoln Road",
    town: "Newark",
    county: "Nottinghamshire",
    postcode: "NG24 2NY",
    latitude: 53.1007,
    longitude: -0.7584,
    price_text: "From GBP 7",
    booking_required: false,
    booking_url: "https://www.newarkshowground.com/",
    organiser_name: "Newark Showground",
    organiser_url: "https://www.newarkshowground.com/",
    image_url: null,
    status: "published",
    confidence_score: 78,
    is_verified: false,
    source_count: 1,
    last_checked_at: "2026-05-01T12:00:00Z"
  },
  {
    id: "sample-5",
    title: "Goodwood Breakfast Club Vintage Sunday",
    slug: "goodwood-breakfast-club-vintage-sunday",
    description: "Early morning paddock meet for vintage, pre-war and cherished classics at the motor circuit.",
    event_type: "Vintage / pre-war",
    start_date: "2026-08-02",
    start_time: "07:30",
    end_date: null,
    end_time: null,
    venue_name: "Goodwood Motor Circuit",
    address: "Goodwood",
    town: "Chichester",
    county: "West Sussex",
    postcode: "PO18 0PH",
    latitude: 50.8594,
    longitude: -0.7596,
    price_text: "Registration required",
    booking_required: true,
    booking_url: "https://www.goodwood.com/",
    organiser_name: "Goodwood",
    organiser_url: "https://www.goodwood.com/",
    image_url: null,
    status: "published",
    confidence_score: 88,
    is_verified: true,
    source_count: 2,
    last_checked_at: "2026-05-04T09:15:00Z"
  },
  {
    id: "sample-6",
    title: "Cotswold Classic Road Run",
    slug: "cotswold-classic-road-run",
    description: "Scenic road run for pre-1985 vehicles, finishing with a village green display and charity raffle.",
    event_type: "Rally / road run",
    start_date: "2026-06-28",
    start_time: "09:30",
    end_date: null,
    end_time: null,
    venue_name: "Cirencester Market Place",
    address: "Market Place",
    town: "Cirencester",
    county: "Gloucestershire",
    postcode: "GL7 2NY",
    latitude: 51.7175,
    longitude: -1.9682,
    price_text: "GBP 20 entry",
    booking_required: true,
    booking_url: "https://example.org/cotswold-classic-road-run",
    organiser_name: "Cotswold Classic Car Club",
    organiser_url: "https://example.org/cotswold-classic-road-run",
    image_url: null,
    status: "published",
    confidence_score: 76,
    is_verified: false,
    source_count: 1,
    last_checked_at: "2026-05-04T11:00:00Z"
  },
  {
    id: "sample-7",
    title: "Manchester Mini Owners Evening Meet",
    slug: "manchester-mini-owners-evening-meet",
    description: "Monthly marque meet for classic Mini and Austin owners with informal parking and cafe access.",
    event_type: "Austin / Mini / marque-specific",
    start_date: "2026-05-22",
    start_time: "18:30",
    end_date: null,
    end_time: null,
    venue_name: "The Runway Visitor Park",
    address: "Sunbank Lane",
    town: "Altrincham",
    county: "Greater Manchester",
    postcode: "WA15 8XQ",
    latitude: 53.3612,
    longitude: -2.2787,
    price_text: "Parking charge",
    booking_required: false,
    booking_url: "https://example.org/mini-meet",
    organiser_name: "Manchester Mini Owners",
    organiser_url: "https://example.org/mini-meet",
    image_url: null,
    status: "published",
    confidence_score: 72,
    is_verified: false,
    source_count: 1,
    last_checked_at: "2026-05-04T18:00:00Z"
  },
  {
    id: "sample-8",
    title: "American Classics at Beaulieu",
    slug: "american-classics-at-beaulieu",
    description: "American classics, hot rods, customs and muscle cars displayed in the National Motor Museum grounds.",
    event_type: "American / hot rod",
    start_date: "2026-09-06",
    start_time: "10:00",
    end_date: null,
    end_time: null,
    venue_name: "National Motor Museum",
    address: "Beaulieu",
    town: "Brockenhurst",
    county: "Hampshire",
    postcode: "SO42 7ZN",
    latitude: 50.8238,
    longitude: -1.4533,
    price_text: "Admission applies",
    booking_required: true,
    booking_url: "https://www.beaulieu.co.uk/",
    organiser_name: "Beaulieu",
    organiser_url: "https://www.beaulieu.co.uk/",
    image_url: null,
    status: "published",
    confidence_score: 84,
    is_verified: true,
    source_count: 1,
    last_checked_at: "2026-05-02T13:00:00Z"
  }
];

export const sampleAgentRuns: AgentRun[] = [
  {
    id: "run-1",
    run_type: "morning",
    started_at: "2026-05-05T05:00:00Z",
    finished_at: "2026-05-05T05:03:12Z",
    status: "completed",
    searches_performed: 44,
    results_found: 118,
    events_created: 7,
    events_updated: 14,
    duplicates_found: 22,
    notes: "Mock provider run for local development."
  }
];

export const sampleReviewItems: ReviewQueueItemType[] = [
  {
    id: "review-1",
    proposed_event: {
      title: "Sunday Classics at the Old Mill",
      event_type: "Club meet",
      town: "Shrewsbury",
      start_date: "2026-05-10"
    },
    source_url: "https://example.org/sunday-classics",
    reason: "Single source and venue postcode missing.",
    confidence_score: 64,
    status: "pending",
    created_at: "2026-05-05T12:00:00Z"
  }
];
