import type { Metadata } from "next";
import Link from "next/link";
import { requireViewer } from "@/lib/auth";
import { getGoingEvents, getSavedEvents } from "@/lib/events";
import { createClient } from "@/lib/supabase/server";
import type { ClassicEvent } from "@/lib/types";
import { changeRoadbook } from "./actions";
import { RoadbookButton } from "./SubmitButton";
export const metadata: Metadata = { title: "My Roadbooks", robots: { index: false, follow: false } };
const input = "mt-1 w-full rounded-md border border-ink/20 bg-paper p-3";
const button = "focus-ring inline-flex min-h-11 items-center justify-center rounded-md bg-racing px-4 py-2 text-sm font-bold text-paper";
export default async function MyEventsPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const viewer = await requireViewer("/my-events");
  if (!viewer.canUseRoadbook) return <section className="mx-auto max-w-3xl px-4 py-14"><h1 className="font-serif text-5xl">Your weekends, beautifully organised.</h1><p className="mt-5 leading-7">Roadbook brings together a private event wishlist, weekend collections, personal notes, shareable plans and calendar downloads. It is available to invited early-access members while paid membership is being prepared.</p><Link href="/membership" className={`${button} mt-6`}>Explore Roadbook</Link><Link href="/account?tab=going" className="ml-5 font-bold underline">My going events</Link></section>;
  const params = await searchParams; const supabase = await createClient();
  const [{ data: books, error }, saved, going] = await Promise.all([supabase.from("roadbooks").select("id,name,description,is_shared,share_token").eq("user_id", viewer.id).order("created_at", { ascending: false }), getSavedEvents(viewer.id), getGoingEvents(viewer.id)]);
  const book = (books || []).find((item) => item.id === params.book) || books?.[0];
  const { data: rows } = book ? await supabase.from("roadbook_events").select("event_id,position,notes,events(*)").eq("roadbook_id", book.id).order("position").order("created_at") : { data: [] };
  const stops = (rows || []).map((row) => ({ ...row, event: row.events as unknown as ClassicEvent | null }));
  const choices = [...new Map([...saved, ...going].map((event) => [event.id, event])).values()].filter((event) => !stops.some((stop) => stop.event_id === event.id));
  return <section className="mx-auto max-w-6xl px-4 py-10 sm:px-6"><p className="text-sm font-bold uppercase tracking-widest text-oxblood">Roadbook membership</p><h1 className="mt-2 font-serif text-5xl">Plan your next great weekend.</h1><p className="mt-4 text-muted">Private by default. Collect events, order your stops and keep the details together.</p>
    <div className="my-5 flex flex-wrap gap-5 font-bold text-racing"><Link href="/account?tab=saved">Private wishlist →</Link><Link href="/account?tab=going">Going events →</Link><Link href="/events?radius=uk">Find more events →</Link></div>
    {error || (params.notice && params.notice !== "saved") ? <p role="alert" className="mb-5 rounded-md bg-oxblood/10 p-4">That change could not be completed. Check your details and try again.</p> : params.notice === "saved" ? <p role="status" className="mb-5 rounded-md bg-racing/10 p-4">Your Roadbook has been saved.</p> : null}
    <div className="grid gap-7 lg:grid-cols-[280px_1fr]"><aside className="rounded-xl border border-ink/10 bg-paper p-5"><h2 className="font-serif text-2xl">Your roadbooks</h2><ul className="my-5 space-y-3">{books?.map((item) => <li key={item.id}><Link aria-current={item.id === book?.id ? "page" : undefined} className="font-bold underline" href={`/my-events?book=${item.id}`}>{item.name}</Link></li>)}</ul><form action={changeRoadbook}><input type="hidden" name="action" value="create"/><label className="text-sm font-bold">New roadbook<input className={input} name="name" placeholder="A Sunday in Yorkshire" minLength={2} maxLength={100} required/></label><RoadbookButton className={`${button} mt-3`}>Create roadbook</RoadbookButton></form></aside><div>{book ? <>
      <form action={changeRoadbook} className="space-y-4 rounded-xl border border-ink/10 bg-paper p-6"><Hidden action="details" book={book.id}/><label className="block text-sm font-bold">Roadbook name<input className={input} name="name" defaultValue={book.name} minLength={2} maxLength={100} required/></label><label className="block text-sm font-bold">Plan summary (included when sharing)<textarea className={input} name="description" defaultValue={book.description} maxLength={2000} rows={3}/></label><label className="flex items-center gap-3 text-sm"><input type="checkbox" name="is_shared" defaultChecked={book.is_shared}/>Enable a link anyone with the link can view. Stop notes remain private.</label><RoadbookButton className={button}>Save details</RoadbookButton></form>
      <div className="my-5 flex flex-wrap gap-5 font-bold text-racing"><a href={`/my-events/${book.id}/calendar`}>Download calendar (.ics) ↓</a>{book.is_shared ? <Link href={`/roadbook/${book.share_token}`}>Open shareable plan →</Link> : null}</div><p className="mb-4 text-sm text-muted">Calendar downloads use all-day reminders. Always check organiser timings and booking before travelling.</p><h2 className="font-serif text-3xl">Your stops</h2>
      {stops.length ? stops.map((stop) => <article key={stop.event_id} className="my-4 rounded-xl border border-ink/10 bg-paper p-5"><Link className="text-lg font-bold underline" href={stop.event ? `/events/${stop.event.slug}` : "/events?radius=uk"}>{stop.event?.title || "Event no longer available"}</Link><p className="my-2 text-sm text-muted">{stop.event?.start_date} · {stop.event?.venue_name} · {stop.event?.town}</p><form action={changeRoadbook} className="space-y-3"><Hidden action="notes" book={book.id} event={stop.event_id}/><label className="block text-sm font-bold">Stop order<input className={`${input} max-w-24`} type="number" name="position" min={0} max={999} defaultValue={stop.position} required/></label><label className="block text-sm font-bold">Private notes<textarea className={input} name="notes" defaultValue={stop.notes} maxLength={2000} rows={2}/></label><RoadbookButton className={button}>Save stop</RoadbookButton></form><form action={changeRoadbook} className="mt-3"><Hidden action="remove" book={book.id} event={stop.event_id}/><RoadbookButton className="min-h-11 text-sm font-bold text-oxblood underline">Remove stop</RoadbookButton></form></article>) : <p className="my-5 text-muted">Add events from your wishlist or going list to start this roadbook.</p>}
      {choices.length ? <form action={changeRoadbook} className="mt-6 rounded-xl bg-cream p-5"><Hidden action="add" book={book.id}/><label className="block text-sm font-bold">Add a saved or going event<select className={input} name="event_id" required>{choices.map((event) => <option key={event.id} value={event.id}>{event.start_date} — {event.title}</option>)}</select></label><RoadbookButton className={`${button} mt-3`}>Add to roadbook</RoadbookButton></form> : null}
      <details className="mt-9 text-sm"><summary className="cursor-pointer font-bold text-oxblood">Delete this roadbook</summary><p className="my-3">This permanently removes the plan and its stop notes. Your saved and going events remain.</p><form action={changeRoadbook}><Hidden action="delete" book={book.id}/><RoadbookButton className="min-h-11 font-bold text-oxblood underline">Permanently delete roadbook</RoadbookButton></form></details>
    </> : <p className="rounded-xl bg-cream p-8">Create your first roadbook to bring a weekend together.</p>}</div></div></section>;
}
function Hidden({ action, book, event }: { action: string; book: string; event?: string }) { return <><input type="hidden" name="action" value={action}/><input type="hidden" name="roadbook_id" value={book}/>{event ? <input type="hidden" name="event_id" value={event}/> : null}</>; }
