insert into public.events (
  title, slug, description, event_type, start_date, start_time, venue_name, address, town, county, postcode,
  latitude, longitude, price_text, booking_required, booking_url, organiser_name, organiser_url,
  status, confidence_score, is_verified, source_count, last_checked_at
) values
('Bicester Heritage Scramble', 'bicester-heritage-scramble-2026', 'A relaxed open-day gathering with historic motoring specialists, club displays and food around the former RAF site.', 'Classic car show', '2026-06-21', '09:00', 'Bicester Heritage', 'Buckingham Road', 'Bicester', 'Oxfordshire', 'OX27 8AL', 51.9159, -1.1401, 'Advance tickets', true, 'https://bicesterheritage.co.uk/', 'Bicester Heritage', 'https://bicesterheritage.co.uk/', 'published', 90, true, 2, now()),
('Brooklands Summer Classic Gathering', 'brooklands-summer-classic-gathering', 'Classic cars, period displays and museum access at one of Britain''s most important motoring venues.', 'Museum / venue event', '2026-07-12', '10:00', 'Brooklands Museum', 'Brooklands Drive', 'Weybridge', 'Surrey', 'KT13 0SL', 51.3536, -0.4656, 'Museum admission applies', false, 'https://www.brooklandsmuseum.com/', 'Brooklands Museum', 'https://www.brooklandsmuseum.com/', 'published', 86, true, 1, now()),
('Haynes Breakfast Club Classics', 'haynes-breakfast-club-classics', 'Cars and coffee style Sunday meet for classic, sports and interesting vehicles at Haynes Motor Museum.', 'Cars & coffee', '2026-05-17', '08:30', 'Haynes Motor Museum', 'Sparkford', 'Yeovil', 'Somerset', 'BA22 7LH', 51.0396, -2.5607, 'Free meet, museum extra', false, 'https://www.haynesmuseum.org/', 'Haynes Motor Museum', 'https://www.haynesmuseum.org/', 'published', 82, false, 1, now()),
('Newark Autojumble and Classic Parts Day', 'newark-autojumble-classic-parts-day', 'Autojumble stalls, restoration parts, automobilia and club parking for classic vehicle owners.', 'Autojumble', '2026-06-07', '09:00', 'Newark Showground', 'Lincoln Road', 'Newark', 'Nottinghamshire', 'NG24 2NY', 53.1007, -0.7584, 'From GBP 7', false, 'https://www.newarkshowground.com/', 'Newark Showground', 'https://www.newarkshowground.com/', 'published', 78, false, 1, now()),
('Goodwood Breakfast Club Vintage Sunday', 'goodwood-breakfast-club-vintage-sunday', 'Early morning paddock meet for vintage, pre-war and cherished classics at the motor circuit.', 'Vintage / pre-war', '2026-08-02', '07:30', 'Goodwood Motor Circuit', 'Goodwood', 'Chichester', 'West Sussex', 'PO18 0PH', 50.8594, -0.7596, 'Registration required', true, 'https://www.goodwood.com/', 'Goodwood', 'https://www.goodwood.com/', 'published', 88, true, 2, now()),
('Cotswold Classic Road Run', 'cotswold-classic-road-run', 'Scenic road run for pre-1985 vehicles, finishing with a village green display and charity raffle.', 'Rally / road run', '2026-06-28', '09:30', 'Cirencester Market Place', 'Market Place', 'Cirencester', 'Gloucestershire', 'GL7 2NY', 51.7175, -1.9682, 'GBP 20 entry', true, 'https://example.org/cotswold-classic-road-run', 'Cotswold Classic Car Club', 'https://example.org/cotswold-classic-road-run', 'published', 76, false, 1, now()),
('Manchester Mini Owners Evening Meet', 'manchester-mini-owners-evening-meet', 'Monthly marque meet for classic Mini and Austin owners with informal parking and cafe access.', 'Austin / Mini / marque-specific', '2026-05-22', '18:30', 'The Runway Visitor Park', 'Sunbank Lane', 'Altrincham', 'Greater Manchester', 'WA15 8XQ', 53.3612, -2.2787, 'Parking charge', false, 'https://example.org/mini-meet', 'Manchester Mini Owners', 'https://example.org/mini-meet', 'published', 72, false, 1, now()),
('American Classics at Beaulieu', 'american-classics-at-beaulieu', 'American classics, hot rods, customs and muscle cars displayed in the National Motor Museum grounds.', 'American / hot rod', '2026-09-06', '10:00', 'National Motor Museum', 'Beaulieu', 'Brockenhurst', 'Hampshire', 'SO42 7ZN', 50.8238, -1.4533, 'Admission applies', true, 'https://www.beaulieu.co.uk/', 'Beaulieu', 'https://www.beaulieu.co.uk/', 'published', 84, true, 1, now()),
('Llandudno Promenade Classic Display', 'llandudno-promenade-classic-display', 'Seaside club display featuring cherished classics, light commercials and local charity stands.', 'Club meet', '2026-07-19', '10:30', 'Llandudno Promenade', 'The Promenade', 'Llandudno', 'Conwy', 'LL30 2LP', 53.3241, -3.8276, 'Free spectator entry', false, 'https://example.org/llandudno-classics', 'North Wales Classic Vehicle Club', 'https://example.org/llandudno-classics', 'published', 74, false, 1, now()),
('Scottish Vintage Vehicle Rally', 'scottish-vintage-vehicle-rally', 'Vintage and pre-war vehicles, road run arrivals, trade stands and family displays.', 'Vintage / pre-war', '2026-08-23', '10:00', 'Scone Palace Parklands', 'Scone Palace', 'Perth', 'Perthshire', 'PH2 6BD', 56.4236, -3.4389, 'Admission applies', true, 'https://example.org/scottish-vintage-rally', 'Scottish Vintage Vehicle Federation', 'https://example.org/scottish-vintage-rally', 'published', 79, false, 1, now())
on conflict (slug) do nothing;
