-- Curated discovery sources only; this migration contains no event rows.
insert into public.source_registry (source_key,source_name,domain,start_url,source_type,format_hint,country_code,region,priority_weight,crawl_frequency,requires_review,is_active,notes) values
  ('classic-shows-uk','Classic Shows UK','classicshowsuk.co.uk','https://classicshowsuk.co.uk/classic-car-shows-this-year/','aggregator','html','GB',null,94,'six_hourly',false,true,''),
  ('classic-sports-car-calendar','Classic & Sports Car Calendar','classicandsportscar.com','https://www.classicandsportscar.com/calendar','aggregator','html','GB',null,91,'six_hourly',false,true,''),
  ('fbhvc','Federation of British Historic Vehicle Clubs','fbhvc.co.uk','https://www.fbhvc.co.uk/events','federation','html','GB',null,92,'daily',false,true,''),
  ('historic-vehicle-events','Historic Vehicle Events','historic-vehicle-events.com','https://www.historic-vehicle-events.com/','aggregator','html','GB',null,82,'daily',false,true,''),
  ('car-calendar','Car Calendar','carcalendar.co.uk','https://www.carcalendar.co.uk/','aggregator','html','GB',null,80,'daily',false,true,''),
  ('car-events','CarEvents.com','carevents.com','https://www.carevents.com/events/','aggregator','search','GB',null,68,'daily',true,true,'Competitor/link discovery only; direct crawling is disabled unless a mapped public event URL is independently permitted.'),
  ('eventbrite-uk-classic','Eventbrite UK classic-car search','eventbrite.co.uk','https://www.eventbrite.co.uk/d/united-kingdom/classic-car/','marketplace','search','GB',null,72,'daily',true,true,''),
  ('facebook-public-events','Facebook public events','facebook.com','https://www.facebook.com/events/','social','search','GB',null,68,'daily',true,false,'Reserved for a future reviewed search connector; no private content or login bypass.'),
  ('beaulieu-events','National Motor Museum, Beaulieu','beaulieu.co.uk','https://www.beaulieu.co.uk/events/','museum','html','GB','South East England',94,'six_hourly',false,true,''),
  ('british-motor-museum','British Motor Museum','britishmotormuseum.co.uk','https://www.britishmotormuseum.co.uk/whats-on','museum','html','GB','West Midlands',94,'six_hourly',false,true,''),
  ('brooklands','Brooklands Museum','brooklandsmuseum.com','https://www.brooklandsmuseum.com/whats-on','museum','html','GB','South East England',93,'six_hourly',false,true,''),
  ('haynes-museum','Haynes Motor Museum','haynesmuseum.org','https://www.haynesmuseum.org/events','museum','html','GB','South West England',91,'daily',false,true,''),
  ('coventry-transport-museum','Coventry Transport Museum','transport-museum.com','https://www.transport-museum.com/events','museum','html','GB','West Midlands',80,'daily',false,true,''),
  ('lakeland-motor-museum','Lakeland Motor Museum','lakelandmotormuseum.co.uk','https://www.lakelandmotormuseum.co.uk/events/','museum','html','GB','North West England',78,'daily',false,true,''),
  ('national-motor-museum','National Motor Museum Trust','nationalmotormuseum.org.uk','https://nationalmotormuseum.org.uk/events/','museum','html','GB','South East England',80,'daily',false,true,''),
  ('grampian-transport-museum','Grampian Transport Museum','gtm.org.uk','https://www.gtm.org.uk/events/','museum','html','GB','Scotland',78,'daily',false,true,''),
  ('museum-of-power','Museum of Power','museumofpower.org.uk','https://www.museumofpower.org.uk/events/','museum','html','GB','East of England',75,'daily',false,true,''),
  ('bicester-heritage','Bicester Heritage','bicesterheritage.co.uk','https://bicesterheritage.co.uk/events/','organiser','html','GB','South East England',95,'six_hourly',false,true,''),
  ('goodwood-motorsport','Goodwood Motorsport','goodwood.com','https://www.goodwood.com/motorsport/','motorsport','html','GB','South East England',94,'six_hourly',false,true,''),
  ('silverstone-events','Silverstone Events','silverstone.co.uk','https://www.silverstone.co.uk/events','motorsport','html','GB','East Midlands',88,'daily',false,true,''),
  ('motor-sport-vision','MotorSport Vision Events','msv.com','https://www.msv.com/calendar','motorsport','html','GB',null,84,'daily',false,true,''),
  ('castle-combe','Castle Combe Circuit','castlecombecircuit.co.uk','https://castlecombecircuit.co.uk/shows/','motorsport','html','GB','South West England',84,'daily',false,true,''),
  ('prescott-hill-climb','Prescott Speed Hill Climb','prescotthillclimb.co.uk','https://www.prescotthillclimb.co.uk/events/','motorsport','html','GB','South West England',83,'daily',false,true,''),
  ('shelsley-walsh','Shelsley Walsh','shelsleywalsh.com','https://www.shelsleywalsh.com/events','motorsport','html','GB','West Midlands',83,'daily',false,true,''),
  ('harewood-hill','Harewood Speed Hillclimb','harewoodhill.com','https://www.harewoodhill.com/events/','motorsport','html','GB','Yorkshire and the Humber',78,'daily',false,true,''),
  ('santa-pod','Santa Pod Raceway','santapod.co.uk','https://santapod.co.uk/calendar.php','motorsport','html','GB','East of England',80,'daily',false,true,''),
  ('classic-motor-show','Lancaster Insurance Classic Motor Show','necclassicmotorshow.com','https://www.necclassicmotorshow.com/whats-on','organiser','html','GB','West Midlands',91,'daily',false,true,''),
  ('restoration-show','Practical Classics Restoration Show','necrestorationshow.com','https://www.necrestorationshow.com/whats-on','organiser','html','GB','West Midlands',87,'daily',false,true,''),
  ('caffeine-machine','Caffeine & Machine','caffeineandmachine.com','https://caffeineandmachine.com/pages/whats-on','organiser','html','GB','England',81,'daily',false,true,''),
  ('ace-cafe-london','Ace Cafe London','london.acecafe.com','https://london.acecafe.com/meets/','organiser','html','GB','London',80,'daily',false,true,''),
  ('retro-rides','Retro Rides','forum.retro-rides.org','https://forum.retro-rides.org/board/13/events-shows','club','html','GB',null,70,'daily',true,true,''),
  ('mg-car-club','MG Car Club','mgcc.co.uk','https://www.mgcc.co.uk/events/','club','html','GB',null,85,'daily',false,true,''),
  ('tr-register','TR Register','tr-register.co.uk','https://www.tr-register.co.uk/events','club','html','GB',null,82,'daily',false,true,''),
  ('austin-healey-club','Austin Healey Club','austinhealeyclub.com','https://www.austinhealeyclub.com/events/','club','html','GB',null,79,'daily',false,true,''),
  ('jaguar-enthusiasts','Jaguar Enthusiasts'' Club','jec.org.uk','https://jec.org.uk/events','club','html','GB',null,80,'daily',false,true,''),
  ('porsche-club-gb','Porsche Club Great Britain','porscheclubgb.com','https://www.porscheclubgb.com/events','club','html','GB',null,78,'daily',false,true,''),
  ('bmw-car-club-gb','BMW Car Club GB','bmwcarclubgb.uk','https://bmwcarclubgb.uk/events/','club','html','GB',null,74,'daily',false,true,''),
  ('alfa-romeo-owners','Alfa Romeo Owners Club UK','aroc-uk.com','https://www.aroc-uk.com/events/','club','html','GB',null,76,'daily',false,true,''),
  ('rolls-royce-enthusiasts','Rolls-Royce Enthusiasts'' Club','rrec.org.uk','https://rrec.org.uk/events','club','html','GB',null,73,'daily',false,true,''),
  ('mini-cooper-register','Mini Cooper Register','minicooper.org','https://www.minicooper.org/events/','club','html','GB',null,76,'daily',false,true,''),
  ('national-street-rod','National Street Rod Association UK','nsra.org.uk','https://www.nsra.org.uk/events/','club','html','GB',null,74,'daily',false,true,''),
  ('visit-hampshire','Visit Hampshire What''s On','visit-hampshire.co.uk','https://www.visit-hampshire.co.uk/whats-on','council','html','GB','Hampshire',58,'daily',true,true,''),
  ('visit-kent','Visit Kent What''s On','visitkent.co.uk','https://www.visitkent.co.uk/whats-on/','council','html','GB','Kent',58,'daily',true,true,''),
  ('visit-devon','Visit Devon What''s On','visitdevon.co.uk','https://www.visitdevon.co.uk/whats-on/','council','html','GB','Devon',58,'daily',true,true,''),
  ('visit-yorkshire','Visit Yorkshire Events','yorkshire.com','https://www.yorkshire.com/events/','council','html','GB','Yorkshire',58,'daily',true,true,''),
  ('visit-scotland','VisitScotland Events','visitscotland.com','https://www.visitscotland.com/things-to-do/events','council','html','GB','Scotland',60,'daily',true,true,''),
  ('visit-wales','Visit Wales Events','visitwales.com','https://www.visitwales.com/things-do/events','council','html','GB','Wales',60,'daily',true,true,''),
  ('discover-ni','Discover Northern Ireland What''s On','discovernorthernireland.com','https://discovernorthernireland.com/whats-on','council','html','GB','Northern Ireland',60,'daily',true,true,''),
  ('fiva-events','FIVA International Events','fiva.org','https://www.fiva.org/en/events/','federation','html','FR','Europe',94,'six_hourly',false,true,''),
  ('retromobile','Rétromobile','retromobile.com','https://www.retromobile.com/en-gb.html','organiser','html','FR','France',90,'daily',false,true,''),
  ('lemans-classic','Le Mans Classic','lemansclassic.com','https://www.lemansclassic.com/en/','motorsport','html','FR','France',92,'daily',false,true,''),
  ('cite-automobile','Cité de l''Automobile','musee-national-automobile.fr','https://www.musee-national-automobile.fr/en/agenda','museum','html','FR','France',78,'daily',false,true,''),
  ('techno-classica','Techno-Classica Essen','siha.de','https://www.siha.de/tce.php','organiser','html','DE','Germany',89,'daily',false,true,''),
  ('retro-classics','Retro Classics Stuttgart','retro-classics.de','https://www.retro-classics.de/en/','organiser','html','DE','Germany',88,'daily',false,true,''),
  ('classic-days','Classic Days','classic-days.de','https://www.classic-days.de/','organiser','html','DE','Germany',85,'daily',false,true,''),
  ('avd-oldtimer','AvD Oldtimer Grand Prix','oldtimergrandprix.com','https://oldtimergrandprix.com/en/','motorsport','html','DE','Germany',88,'daily',false,true,''),
  ('interclassics','InterClassics','interclassics.events','https://interclassics.events/en/','organiser','html','BE','Belgium and Netherlands',88,'daily',false,true,''),
  ('autoworld-brussels','Autoworld Brussels','autoworld.be','https://www.autoworld.be/en/agenda','museum','html','BE','Belgium',78,'daily',false,true,''),
  ('louwman-museum','Louwman Museum','louwmanmuseum.nl','https://www.louwmanmuseum.nl/en/whats-on/','museum','html','NL','Netherlands',79,'daily',false,true,''),
  ('auto-moto-epoca','Auto e Moto d''Epoca','autoemotodepoca.com','https://autoemotodepoca.com/en/','organiser','html','IT','Italy',89,'daily',false,true,''),
  ('mille-miglia','1000 Miglia','1000miglia.it','https://1000miglia.it/en/events/','motorsport','html','IT','Italy',91,'daily',false,true,''),
  ('museo-automobile-torino','Museo Nazionale dell''Automobile','museoauto.com','https://www.museoauto.com/en/events/','museum','html','IT','Italy',77,'daily',false,true,''),
  ('auto-retro-barcelona','AutoRetro Barcelona','autoretro.es','https://www.autoretro.es/','organiser','html','ES','Spain',82,'daily',false,true,''),
  ('classic-madrid','ClassicMadrid','classicmadrid.com','https://www.classicmadrid.com/','organiser','html','ES','Spain',82,'daily',false,true,''),
  ('spirit-of-jarama','Jarama Classic','jarama.org','https://www.jarama.org/','motorsport','html','ES','Spain',72,'daily',true,true,''),
  ('lisboa-classicos','Salão Motorclássico','motorclassico.com','https://www.motorclassico.com/','organiser','html','PT','Portugal',78,'daily',false,true,''),
  ('classic-car-house','Classic Car House','classiccarhouse.dk','https://classiccarhouse.dk/en/events/','museum','html','DK','Denmark',72,'daily',false,true,''),
  ('automobilmuseum-prototyp','PROTOTYP Museum','prototyp-hamburg.de','https://prototyp-hamburg.de/en/events/','museum','html','DE','Germany',70,'daily',false,true,''),
  ('classic-car-auctions-events','Classic Car Auctions Europe Events','classiccar-auctions.com','https://www.classiccar-auctions.com/en/events','marketplace','html','NL','Europe',65,'daily',true,true,'')
on conflict (source_key) do update set source_name=excluded.source_name,domain=excluded.domain,start_url=excluded.start_url,source_type=excluded.source_type,format_hint=excluded.format_hint,country_code=excluded.country_code,region=excluded.region,priority_weight=excluded.priority_weight,crawl_frequency=excluded.crawl_frequency,requires_review=excluded.requires_review,notes=excluded.notes,updated_at=now();
